[project]
name = "scorestream2-core"
version = "0.1.0"
description = ""
authors = [
    {name = "jingxin",email = "xujingxin07@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "music21 (>=9.3.0,<10.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"

[tool.poetry]
package-mode = false